# Generated by Django 3.1 on 2021-09-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0003_auto_20210902_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifyconfig',
            name='telegram_bad_key_text',
            field=models.TextField(blank=True, default='Неправильный уникальный код. Пожалуйста, свяжитесь с техподдержкой', verbose_name='Telegram - Текст ошибки кода бота'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='telegram_failed_added_text',
            field=models.TextField(blank=True, default='Ошибка при привязке учетной записи. Пожалуйста, свяжитесь с техподдержкой', verbose_name='Telegram - Текст провал, не добавлен код'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='telegram_help_text',
            field=models.TextField(blank=True, default='Используйте команду /set <уникальный код> для того, чтобы получать сообщения от бота. Уникальный код вы можете получить на нашем сайте', verbose_name='Telegram - Текст помощи бота'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='telegram_success_added_text',
            field=models.TextField(blank=True, default='Ваша учетная запись успешно привязана к боту. Вы будете получать уведомления!', verbose_name='Telegram - Текст успешно добавлен код'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='telegram_welcome_text',
            field=models.TextField(blank=True, default='Добрый день! Здесь вы можете получать уведомления от нашего сайта', verbose_name='Telegram - Приветственный текст бота'),
        ),
    ]
