# Generated by Django 3.1 on 2022-04-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0007_auto_20220401_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifyconfig',
            name='sms_password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Пароль для api СМС провайдера'),
        ),
    ]
