# Generated by Django 3.1 on 2022-04-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0010_auto_20220413_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifycategory',
            name='template',
            field=models.TextField(default='{{text}}', verbose_name='Простой шаблон'),
        ),
    ]
