# Generated by Django 3.1 on 2022-06-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0022_auto_20220518_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='event',
            field=models.IntegerField(blank=True, choices=[(1, 'Register'), (2, 'Register call code'), (3, 'Feeback'), (4, 'Example 1'), (5, 'Example 2'), (6, 'TestEvent')], null=True, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='notifytemplate',
            name='event',
            field=models.IntegerField(blank=True, choices=[(1, 'Register'), (2, 'Register call code'), (3, 'Feeback'), (4, 'Example 1'), (5, 'Example 2'), (6, 'TestEvent')], null=True, verbose_name='Событие'),
        ),
    ]
