# Generated by Django 3.1 on 2022-06-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0026_auto_20220601_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifyconfig',
            name='telegram_allow_sending_without_reply',
            field=models.BooleanField(default=False, verbose_name='Разрешить, если сообщение должно быть отправлено, даже если ответное сообщение не найдено'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='telegram_disable_notification',
            field=models.BooleanField(default=False, verbose_name='Пользователи получат уведомление без звука'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='telegram_disable_web_page_preview',
            field=models.BooleanField(default=False, verbose_name='Отключает предварительный просмотр ссылок в сообщениях'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='telegram_parse_mode',
            field=models.CharField(blank=True, choices=[('', 'Без формаитрования'), ('HTML', 'HTML'), ('Markdown', 'Markdown')], default='', max_length=100, verbose_name='Тип парсера телеграм сообщений'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='telegram_timeout',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Тайм-аут чтения с сервера'),
        ),
    ]
