# Generated by Django 3.2 on 2022-08-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0033_auto_20220731_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemnotify',
            name='data_json',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Данные JSON'),
        ),
    ]
