# Generated by Django 3.2 on 2022-10-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0034_alter_systemnotify_data_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifytemplate',
            name='is_delete_after',
            field=models.BooleanField(default=False, verbose_name='Удалять после отправки'),
        ),
    ]
