# Generated by Django 3.2 on 2023-03-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0036_notify_is_delete_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnotify',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
