# Generated by Django 3.2 on 2023-04-12 06:36

import ckeditor_uploader.fields
from django.db import migrations, models
import garpix_notify.utils.file
import garpix_notify.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0037_systemnotify_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifytemplate',
            name='zipfile',
            field=models.FileField(blank=True, null=True, upload_to=garpix_notify.utils.file.get_file_path, validators=[garpix_notify.utils.validators.validate_zip]),
        ),
        migrations.AlterField(
            model_name='notifytemplate',
            name='html',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='HTML'),
        ),
    ]
