# Generated by Django 3.2 on 2023-04-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0038_auto_20230412_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifytemplate',
            name='html_from_type',
            field=models.TextField(choices=[('ckeditor', 'Визуальный редактор'), ('zipfile', 'Импорт архива')], default='ckeditor', max_length=8, verbose_name='Способ формирования html'),
        ),
    ]
