# Generated by Django 3.2 on 2023-04-13 12:42

from django.db import migrations, models
import garpix_notify.utils.file
import garpix_notify.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0039_notifytemplate_html_from_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifytemplate',
            name='html_from_type',
            field=models.TextField(choices=[('ckeditor', 'Визуальный редактор'), ('zipfile', 'Загрузка из архива')], default='ckeditor', max_length=8, verbose_name='Способ формирования html'),
        ),
        migrations.AlterField(
            model_name='notifytemplate',
            name='zipfile',
            field=models.FileField(blank=True, null=True, upload_to=garpix_notify.utils.file.get_file_path, validators=[garpix_notify.utils.validators.validate_zip], verbose_name='Файл архива'),
        ),
    ]
